<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Symfony\Component\Intl\Exception\NotImplementedException;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends \Doctrine\ORM\EntityRepository
{

}
