<?php

namespace AppBundle\Repository;

/**
 * UserVuTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVuTopicRepository extends \Doctrine\ORM\EntityRepository
{
}
